name: Validate PR Approvers

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  call-validate-approvers:
    uses: ./.github/workflows/validate-approvers-wf.yml
    with:
      # teams: '[{"team":"sme","approvals":2},{"team":"quality","approvals":1}]'
      teams-file: '${{ github.workspace }}/teams-config.json'
    secrets:
      github-token: ${{ secrets.SAML_GITHUB_TOKEN }}