name: Validate PR Approvers

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  call-validate-approvers:
    uses: ./.github/workflows/validate-approvers-wf.yml
    with:
      config-path: teams.yml
    secrets:
      github-token: ${{ secrets.SAML_GITHUB_TOKEN }}
