name: Validate PR Approvers

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - SME-Approval
  #     - QA-Approval
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize
permissions:
  contents: read
  pull-requests: write
  issues: write
  
jobs:
  call-validate-approvers:
    uses: ./.github/workflows/validate-approvers-wf.yml
    with:
      config-path: teams.yml
    secrets:
      github-token: ${{ secrets.SAML_GITHUB_TOKEN }}
