name: Validate PR Approvers - Workflow Call

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
        description: "Path to the teams configuration file."
    secrets:
      github-token:
        required: true

jobs:
  validate-approvers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python YAML package
        run: pip install pyyaml
      
      - name: Read Config
        run: python ./read-config.py ${{ inputs.config-path }}

      - name: Debug Config
        run: |
          echo  ${{ env.teams }}

      - name: Validate Approvers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.github-token }}
          script: |
            const fs = require('fs');
            const validateApprovers = require('./.github/scripts/validate-approvers.js');
            await validateApprovers({ github, context, core });
