name: Validate PR Approvers - Workflow Call

on:
  workflow_call:
    inputs:
      teams:
        required: true
        type: string
        description: "JSON string representing the teams and required approvals."

jobs:
  validate-approvers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Approvers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SAML_GITHUB_TOKEN }}
          script: |
            const OWNER = context.repo.owner;
            const REPO = context.repo.repo;
            const PR_NUMBER = context.payload.pull_request.number;
            const teamsInput = core.getInput("teams");

            let teams;
            try {
              teams = JSON.parse(teamsInput);
            } catch (error) {
              core.setFailed(`Invalid JSON format for teams input: ${error.message}`);
              return;
            }

            async function getTeamMembers(teamSlug) {
              const members = await github.rest.teams.listMembersInOrg({
                org: OWNER,
                team_slug: teamSlug,
              });
              return members.data.map(member => member.login);
            }

            async function getPRReviews(prNumber) {
              const reviews = await github.rest.pulls.listReviews({
                owner: OWNER,
                repo: REPO,
                pull_number: prNumber,
              });
              return reviews.data.filter(review => review.state === 'APPROVED');
            }

            const reviews = await getPRReviews(PR_NUMBER);

            let approvalCounts = {};
            teams.forEach(team => {
              approvalCounts[team.team] = 0;
            });

            for (const review of reviews) {
              for (const team of teams) {
                const members = await getTeamMembers(team.team);
                if (members.includes(review.user.login)) {
                  approvalCounts[team.team]++;
                }
              }
            }

            for (const team of teams) {
              const required = team.approvals;
              const received = approvalCounts[team.team];

              console.log(`Team: ${team.team}, Required: ${required}, Received: ${received}`);

              if (received < required) {
                core.setFailed(`Requires at least ${required} approvals from ${team.team}. Currently: ${received}`);
              }
            }
